// ai/model.js
// Updated for @google/genai (NEW SDK)

const { GoogleGenAI } = require("@google/genai");
const { findConsultantDeclaration, outOfScopeDeclaration } = require("./tools");

if (!process.env.GEMINI_API_KEY) {
    console.warn("[AI] GEMINI_API_KEY is not set — chat endpoint will fail.");
}

const genAI = new GoogleGenAI({
    apiKey: process.env.GEMINI_API_KEY,
});

// ── System instruction ────────────────────────────────────────────────
const SYSTEM_INSTRUCTION = `
You are VITA-FLOW's AI fitness assistant — a knowledgeable, friendly coach
embedded in a personalised health and fitness platform.

Your role:
- Answer general fitness and nutrition questions directly and confidently.
- Help users understand their diet plans (breakfast, lunch, dinner) and
  weekly workout plans generated by the platform.
- Offer motivation, tips on activity levels (Light / Moderate / Heavy),
  meal preferences (Veg / Non-Veg), and general wellness advice.

When to escalate to a human consultant:
- The user asks for personalised medical advice, injury diagnosis,
  clinical nutrition for a disease, or highly specialised programming.
- In these cases, first ask the user for their preferred consultation
  time (morning, afternoon, or evening), then call find_consultant.

When NOT in scope:
- Legal, financial, unrelated technical, or any non-fitness topic.
- Call out_of_scope and politely redirect the user.

Tone: concise, warm, motivating. Never use medical disclaimers excessively —
one brief note is enough. Always keep responses relevant to VITA-FLOW.
`;

// ⚠️ IMPORTANT: New SDK does NOT use getGenerativeModel the same way
// We define config separately

const modelConfig = {
    model: "gemini-1.5-flash-latest", // ✅ Works in new SDK
    systemInstruction: SYSTEM_INSTRUCTION,
    tools: [
        {
            functionDeclarations: [
                findConsultantDeclaration,
                outOfScopeDeclaration,
            ],
        },
    ],
};

module.exports = { genAI, modelConfig };